"""Train the flood nowcast: stage change at +30/60/90/120 min, with real
uncertainty bands.

HONESTY NOTE, and say this out loud in the pitch:
Sub-hourly gauge data for Indian rivers is not publicly available, so this
trains on sequences generated by the same linear reservoir the simulator uses.
A model trained on its own generator would look implausibly perfect, so three
things are done deliberately:

  1. NOISE. The model never sees truth. Gauge readings carry measurement
     error, rain observations carry multiplicative error, and — most
     importantly — the rainfall FORECAST features carry error that grows with
     lead time, because that is the dominant real-world error source.
  2. SEQUENCE-LEVEL HOLDOUT. Splitting rows at random would leak badly:
     consecutive rows share overlapping feature windows. Whole storm
     sequences are held out instead.
  3. A PERSISTENCE BASELINE. Skill is reported against "assume no change",
     which is what any honest hydrologist asks for first.
  4. SUSTAINED-RAIN COVERAGE. The first version trained only on storms that
     always ended, so it learned "high stage => rain is about to stop" and
     forecast a collapse whenever rain was held steady — exactly the regime a
     demo slider produces. A quarter of sequences are now sustained or
     plateau rain, and forecast features are sometimes generated as a
     persistence forecast (all leads equal), matching how they are served.
  5. OPERATOR STEP CHANGES. A judge dragging the slider from Calm to
     Cloudburst makes rainfall jump instantaneously, which produces rates of
     rise no naturally-ramping storm ever shows. Without those in training the
     model extrapolated wildly (it once forecast a NEGATIVE stage). A fifth of
     sequences are now piecewise-constant step changes.
  6. CALIBRATED INTERVALS. Raw quantile GBMs came out under-confident — the
     nominal 80% band empirically covered ~90%. A band that misstates its own
     confidence is worse than no band, so the interval is rescaled by a factor
     fitted on the VALIDATION split and then verified on test.

The architecture transfers to real gauge data unchanged; only the weights
need recalibration.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from sklearn.ensemble import HistGradientBoostingRegressor

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "api"))
from adapters import BASE_STAGE, advance_reservoir  # noqa: E402  single source of physics

import config as C  # noqa: E402

# ── discretisation ───────────────────────────────────────────────────────
STEP_MIN = 5
STEP_S = STEP_MIN * 60
HORIZONS_MIN = (30, 60, 90, 120)
QUANTILES = (0.1, 0.5, 0.9)
SEQ_HOURS = 24
SEQ_STEPS = SEQ_HOURS * 60 // STEP_MIN          # 288
WARMUP = 24 * 60 // STEP_MIN // 5               # 4.8h of history before first sample

N_SEQUENCES = 1000
SPLIT = (0.70, 0.15, 0.15)                      # train / val / test, BY SEQUENCE
SEED = 11

# ── noise model ──────────────────────────────────────────────────────────
GAUGE_SIGMA_CM = 2.0            # ultrasonic sensor jitter
RAIN_OBS_SIGMA = 0.15           # lognormal, tipping-bucket / radar error
FORECAST_SIGMA = {30: 0.20, 60: 0.30, 120: 0.45}   # grows with lead time

FEATURES = [
    "rain_now", "rain_1h", "rain_3h", "rain_24h",
    "stage_cm", "d_stage_30m", "d_stage_60m",
    "rain_fc_30m", "rain_fc_60m", "rain_fc_120m",
]

OUT_DIR = C.DATA / "nowcast"


# ── synthetic storms ─────────────────────────────────────────────────────
P_SUSTAINED = 0.25          # share of days that are steady rain, not discrete storms
P_STEPS = 0.20              # share of days that are operator-style step changes
P_PERSISTENCE_FC = 0.35     # share of rows whose forecast is "assume it continues"


def rain_sequence(rng: np.random.Generator) -> tuple[np.ndarray, str]:
    """A day of rainfall in mm/hr at STEP_MIN resolution, plus its regime."""
    r = np.zeros(SEQ_STEPS)

    u = rng.random()
    if u < P_STEPS:
        # Piecewise-constant rain: exactly what a slider produces. Includes
        # slams from 0 to very heavy and back, so extreme d_stage is in-sample.
        edges = sorted(rng.choice(np.arange(1, SEQ_STEPS), size=int(rng.integers(2, 7)),
                                  replace=False).tolist())
        bounds = [0, *edges, SEQ_STEPS]
        for a, bnd in zip(bounds, bounds[1:]):
            r[a:bnd] = 0.0 if rng.random() < 0.35 else float(rng.uniform(0, 150))
        return r, "operator_steps"

    if u < P_STEPS + P_SUSTAINED:
        # Steady or slowly-varying rain for hours: the regime an operator
        # creates by parking the slider, and the one monsoon days look like.
        level = float(rng.uniform(5, 130))
        start = int(rng.integers(0, SEQ_STEPS // 2))
        dur = int(rng.integers(24, SEQ_STEPS - start))      # 2 h - rest of day
        drift = rng.normal(0.0, 0.02, dur).cumsum()
        r[start:start + dur] = np.clip(level * (1.0 + drift), 0.0, 200.0)
        return r, "sustained"

    for _ in range(rng.integers(0, 5)):                 # 0-4 storms per day
        start = rng.integers(0, SEQ_STEPS)
        dur = int(rng.integers(2, 36))                  # 10 min - 3 h
        peak = float(rng.uniform(5, 150))
        shape = rng.choice(("triangle", "plateau", "decay"))
        for i in range(dur):
            if start + i >= SEQ_STEPS:
                break
            frac = i / max(1, dur - 1)
            if shape == "triangle":
                w = 1.0 - abs(2 * frac - 1)
            elif shape == "plateau":
                w = 1.0 if 0.15 < frac < 0.85 else 0.4
            else:
                w = float(np.exp(-3 * frac))
            r[start + i] += peak * w
    if rng.random() < 0.3:                              # background drizzle
        r += rng.uniform(0.5, 4.0)
    return np.clip(r, 0.0, 200.0), "storms"


def simulate(rain: np.ndarray) -> np.ndarray:
    """True stage in cm, from the SAME reservoir the simulator uses."""
    stage = np.empty(SEQ_STEPS)
    s = BASE_STAGE
    for i, rr in enumerate(rain):
        s = advance_reservoir(s, float(rr), STEP_S)
        stage[i] = s
    return stage


def _mean_back(a: np.ndarray, i: int, minutes: int) -> float:
    n = max(1, minutes // STEP_MIN)
    return float(a[max(0, i - n + 1): i + 1].mean())


def _mean_fwd(a: np.ndarray, i: int, minutes: int) -> float:
    n = max(1, minutes // STEP_MIN)
    return float(a[i + 1: i + 1 + n].mean()) if i + 1 < len(a) else 0.0


def build_rows(rng: np.random.Generator):
    """Return X, Y (per horizon), and the sequence id of every row."""
    X, seq_ids, regimes = [], [], []
    Y = {h: [] for h in HORIZONS_MIN}

    for sid in range(N_SEQUENCES):
        rain_true, regime = rain_sequence(rng)
        stage_true = simulate(rain_true)

        rain_obs = rain_true * rng.lognormal(0.0, RAIN_OBS_SIGMA, SEQ_STEPS)
        stage_obs = stage_true + rng.normal(0.0, GAUGE_SIGMA_CM, SEQ_STEPS)

        last = SEQ_STEPS - max(HORIZONS_MIN) // STEP_MIN
        for i in range(WARMUP, last):
            d30 = stage_obs[i] - stage_obs[max(0, i - 30 // STEP_MIN)]
            d60 = stage_obs[i] - stage_obs[max(0, i - 60 // STEP_MIN)]

            fc = {}
            if rng.random() < P_PERSISTENCE_FC:
                # Persistence forecast: "it keeps doing what it is doing now".
                # This is literally what scenario mode serves, so the model
                # must have seen identical values across all three leads.
                held = rain_obs[i]
                for lead in FORECAST_SIGMA:
                    fc[lead] = held
            else:
                for lead, sigma in FORECAST_SIGMA.items():
                    true_fc = _mean_fwd(rain_true, i, lead)
                    fc[lead] = true_fc * rng.lognormal(0.0, sigma)

            X.append([
                rain_obs[i],
                _mean_back(rain_obs, i, 60),
                _mean_back(rain_obs, i, 180),
                _mean_back(rain_obs, i, 1440),
                stage_obs[i],
                d30, d60,
                fc[30], fc[60], fc[120],
            ])
            seq_ids.append(sid)
            regimes.append(regime)
            for h in HORIZONS_MIN:
                j = i + h // STEP_MIN
                Y[h].append(stage_true[j] - stage_true[i])   # predict TRUTH

    return (np.asarray(X, dtype="float32"),
            {h: np.asarray(v, dtype="float32") for h, v in Y.items()},
            np.asarray(seq_ids), np.asarray(regimes))


def run() -> None:
    rng = np.random.default_rng(SEED)
    print(f"  generating {N_SEQUENCES} storm sequences ({SEQ_HOURS} h each) …")
    X, Y, seq, regime = build_rows(rng)
    print(f"  {len(X):,} samples x {len(FEATURES)} features")

    # split BY SEQUENCE, never by row
    ids = np.arange(N_SEQUENCES)
    rng.shuffle(ids)
    n_tr = int(SPLIT[0] * N_SEQUENCES)
    n_va = int(SPLIT[1] * N_SEQUENCES)
    tr_ids, va_ids, te_ids = ids[:n_tr], ids[n_tr:n_tr + n_va], ids[n_tr + n_va:]
    tr = np.isin(seq, tr_ids); va = np.isin(seq, va_ids); te = np.isin(seq, te_ids)
    print(f"  split by sequence -> train {tr.sum():,}  val {va.sum():,}  test {te.sum():,}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    import pickle

    report = {"features": FEATURES, "step_min": STEP_MIN, "horizons": list(HORIZONS_MIN),
              "quantiles": list(QUANTILES), "n_samples": int(len(X)),
              "noise": {"gauge_sigma_cm": GAUGE_SIGMA_CM,
                        "rain_obs_sigma": RAIN_OBS_SIGMA,
                        "forecast_sigma": FORECAST_SIGMA},
              "metrics": {}, "calibration": {}}

    models = {}
    calibration: dict[int, float] = {}
    for h in HORIZONS_MIN:
        for q in QUANTILES:
            m = HistGradientBoostingRegressor(
                loss="quantile", quantile=q,
                max_iter=300, learning_rate=0.08, max_depth=6,
                early_stopping=True, validation_fraction=None,
                random_state=SEED,
            )
            m.fit(X[tr], Y[h][tr])
            models[(h, q)] = m

        # ── calibrate the interval on VALIDATION, never on test ──────────
        yv = Y[h][va]
        v10 = models[(h, 0.1)].predict(X[va])
        v50 = models[(h, 0.5)].predict(X[va])
        v90 = models[(h, 0.9)].predict(X[va])

        def coverage(lam: float) -> float:
            lo = v50 - lam * (v50 - v10)
            hi = v50 + lam * (v90 - v50)
            return float(((yv >= lo) & (yv <= hi)).mean())

        lo_l, hi_l = 0.05, 3.0
        for _ in range(40):                       # bisect to 80% coverage
            mid = 0.5 * (lo_l + hi_l)
            if coverage(mid) < 0.80:
                lo_l = mid
            else:
                hi_l = mid
        lam = 0.5 * (lo_l + hi_l)
        calibration[h] = lam

        yt = Y[h][te]
        p10_raw = models[(h, 0.1)].predict(X[te])
        p50 = models[(h, 0.5)].predict(X[te])
        p90_raw = models[(h, 0.9)].predict(X[te])
        p10 = p50 - lam * (p50 - p10_raw)
        p90 = p50 + lam * (p90_raw - p50)

        raw_cover = float(((yt >= p10_raw) & (yt <= p90_raw)).mean())
        mae = float(np.abs(p50 - yt).mean())
        persistence = float(np.abs(yt).mean())          # "assume no change"
        cover = float(((yt >= p10) & (yt <= p90)).mean())
        skill = 1.0 - mae / persistence if persistence else 0.0

        report["metrics"][str(h)] = {
            "mae_cm": round(mae, 2),
            "persistence_mae_cm": round(persistence, 2),
            "skill_vs_persistence": round(skill, 3),
            "p10_p90_coverage": round(cover, 3),
            "raw_coverage_before_calibration": round(raw_cover, 3),
            "calibration_lambda": round(lam, 3),
            "mean_interval_width_cm": round(float((p90 - p10).mean()), 2),
        }
        # Per-regime skill. The headline number is dragged down by
        # operator_steps, which are instantaneous jumps that no forecast can
        # anticipate — real rainfall ramps. Quote both, never just the flattering one.
        by_regime = {}
        for rg in ("storms", "sustained", "operator_steps"):
            sel = te & (regime == rg)
            if sel.sum() < 100:
                continue
            yr = Y[h][sel]
            pr = models[(h, 0.5)].predict(X[sel])
            m_ = float(np.abs(pr - yr).mean())
            p_ = float(np.abs(yr).mean())
            by_regime[rg] = {"mae_cm": round(m_, 2),
                             "persistence_mae_cm": round(p_, 2),
                             "skill": round(1 - m_ / p_ if p_ else 0.0, 3)}
        report["metrics"][str(h)]["by_regime"] = by_regime

        rg_txt = "  ".join(f"{k.split('_')[0]} {v['skill']:.0%}" for k, v in by_regime.items())
        print(f"  +{h:>3} min  MAE {mae:6.2f}  skill {skill:5.1%}  "
              f"band {raw_cover:5.1%}->{cover:5.1%}   [{rg_txt}]")

    # background sample for the Shapley explainer (test rows only — never train)
    bg_idx = rng.choice(np.flatnonzero(te), size=64, replace=False)
    with open(OUT_DIR / "models.pkl", "wb") as fh:
        pickle.dump({"models": models, "features": FEATURES,
                     "calibration": calibration,
                     "background": X[bg_idx]}, fh)
    report["calibration"] = {str(k): round(v, 3) for k, v in calibration.items()}
    (OUT_DIR / "report.json").write_text(json.dumps(report, indent=2))
    print(f"  wrote {OUT_DIR}/models.pkl and report.json")


if __name__ == "__main__":
    run()
